schema = {
    "watch_events" : [
        {"name": "video", "type": "STRING", "mode": "NULLABLE"},
        {"name": "duration", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "ts", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "auth", "type": "STRING", "mode": "NULLABLE"},
        {"name": "level", "type": "STRING", "mode": "NULLABLE"},
        {"name": "city", "type": "STRING", "mode": "NULLABLE"},
        {"name": "state", "type": "STRING", "mode": "NULLABLE"},
        {"name": "userAgent", "type": "STRING", "mode": "NULLABLE"},
        {"name": "lon", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "lat", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "userId", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "lastName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "firstName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "dateOfBirth", "type": "STRING", "mode": "NULLABLE"},
        {"name": "gender", "type": "STRING", "mode": "NULLABLE"},
        {"name": "registration", "type": "INTEGER", "mode": "NULLABLE"}
    ],
    "ad_events": [
        {"name": "video", "type": "STRING", "mode": "NULLABLE"},
        {"name": "adType", "type": "STRING", "mode": "NULLABLE"},
        {"name": "duration", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "ts", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "auth", "type": "STRING", "mode": "NULLABLE"},
        {"name": "level", "type": "STRING", "mode": "NULLABLE"},
        {"name": "city", "type": "STRING", "mode": "NULLABLE"},
        {"name": "state", "type": "STRING", "mode": "NULLABLE"},
        {"name": "userAgent", "type": "STRING", "mode": "NULLABLE"},
        {"name": "lon", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "lat", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "userId", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "lastName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "firstName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "dateOfBirth", "type": "STRING", "mode": "NULLABLE"},
        {"name": "gender", "type": "STRING", "mode": "NULLABLE"},
        {"name": "registration", "type": "INTEGER", "mode": "NULLABLE"}
    ],
    "page_view_events" : [
        {"name": "ts", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "page", "type": "STRING", "mode": "NULLABLE"},
        {"name": "auth", "type": "STRING", "mode": "NULLABLE"},
        {"name": "method", "type": "STRING", "mode": "NULLABLE"},
        {"name": "status", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "level", "type": "STRING", "mode": "NULLABLE"},
        {"name": "city", "type": "STRING", "mode": "NULLABLE"},
        {"name": "state", "type": "STRING", "mode": "NULLABLE"},
        {"name": "userAgent", "type": "STRING", "mode": "NULLABLE"},
        {"name": "lon", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "lat", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "userId", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "lastName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "firstName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "gender", "type": "STRING", "mode": "NULLABLE"},
        {"name": "dateOfBirth", "type": "STRING", "mode": "NULLABLE"},
        {"name": "registration", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "video", "type": "STRING", "mode": "NULLABLE"},
        {"name": "device", "type": "STRING", "mode": "NULLABLE"},
        {"name": "os", "type": "STRING", "mode": "NULLABLE"},
        {"name": "duration", "type": "FLOAT64", "mode": "NULLABLE"}
    ],
    "auth_events" : [
        {"name": "ts", "type": "TIMESTAMP", "mode": "NULLABLE"},
        {"name": "level", "type": "STRING", "mode": "NULLABLE"},
        {"name": "city", "type": "STRING", "mode": "NULLABLE"},
        {"name": "state", "type": "STRING", "mode": "NULLABLE"},
        {"name": "userAgent", "type": "STRING", "mode": "NULLABLE"},
        {"name": "lon", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "lat", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "userId", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "lastName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "firstName", "type": "STRING", "mode": "NULLABLE"},
        {"name": "gender", "type": "STRING", "mode": "NULLABLE"},
        {"name": "dateOfBirth", "type": "STRING", "mode": "NULLABLE"},
        {"name": "registration", "type": "INTEGER", "mode": "NULLABLE"},
        {"name": "device", "type": "STRING", "mode": "NULLABLE"},
        {"name": "os", "type": "STRING", "mode": "NULLABLE"},
        {"name": "success", "type": "BOOLEAN", "mode": "NULLABLE"}
    ]
}

